baseURL = "http://lukewilson.me/"
languageCode = "en-us"
title = "Luke I. Wilson"
enableRobotsTXT = true

[params]
    dateFormat = "Jan 2, 2006"

[permalinks]
    blog = "/blog/:filename/"

[menu]
    [[menu.main]]
        name = "home"
        url = "/"
    [[menu.main]]
        name = "blog"
        url = "/blog/"
    [[menu.main]]
        name = "tags"
        url = "/tags/"
	[[menu.main]]
		name = "quotes"
		url = "/quotes/"

[taxonomies]
    tag = "tags"
	quote = "quotes"
